### ISSUE TITLE
Email case seems to affect Gravatar success

### ISSUE THREAD

**Issue by spearna** [spearna/wall-me#17]
Including an errant capitalization seemed to cause Gravatar not to find a profile that I know is in their database.

**Comment by tessellator** [comment]
We can't help this. The Gravatar API looks email addresses up by hashes of email addresses. The hashes are sensitive to case (since uppercase and lowercase letters have different ASCII values).

I imagine that people tend to type their email address the same everywhere anyway, so I doubt this will be much of an issue.

**Comment by spearna** [comment]
I believe most email addresses are forced lowercase. (Very) Older emails and a few private ones might have capitalization, but I'm thinking it might be okay to force the form to downcase all email input. This will help ensure less errors (and handling).

I think this would be a good base implementation. As we encounter the edge cases, we can handle it. Yea, nea?

**Comment by tessellator** [comment]
I'm not sure I agree with you on this point. We need to let people be able to enter the email address however (with whatever capitalization) they entered it into Gravatar. If we force everything to downcase, we'll be causing email addresses with capital letters to fail to be fetched, and the user won't necessarily know why.

**Comment by spearna** [comment]
Okay. I'll mark this as closed. Possibly handle any "not found" info in the UI form validation issue.
